// <auto-generated />
using System;
using FootballBooking_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballBooking_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322075642_AllowRejectedStatus")]
    partial class AllowRejectedStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_PaymentStatus", "[PaymentStatus] IN ('UNPAID', 'PAID', 'REFUNDED')");

                            t.HasCheckConstraint("CK_Bookings_Status", "[Status] IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'REJECTED')");
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.BookingDetail", b =>
                {
                    b.Property<int>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("PitchId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PlayDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PriceAtBooking")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("DetailId");

                    b.HasIndex("BookingId");

                    b.HasIndex("StaffId");

                    b.HasIndex("PitchId", "PlayDate", "StartTime", "EndTime")
                        .HasDatabaseName("IDX_Booking_Conflict");

                    b.ToTable("BookingDetails", t =>
                        {
                            t.HasCheckConstraint("CK_BookingDetails_Duration", "[DurationMinutes] IN (60, 90, 120)");

                            t.HasCheckConstraint("CK_BookingDetails_Status", "[DetailStatus] IN ('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', 'REJECTED')");
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.BookingStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OldStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailId");

                    b.HasIndex("ChangedBy");

                    b.ToTable("BookingStatusHistory");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayResponseCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GatewayResponseData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IDX_Payments_Booking");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("GatewayTransactionId")
                        .HasDatabaseName("IDX_Payments_Gateway");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_Method", "[PaymentMethod] IN ('WALLET', 'CASH', 'BANK_TRANSFER', 'VNPAY', 'MOMO', 'ZALOPAY')");

                            t.HasCheckConstraint("CK_Payments_Status", "[Status] IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REFUNDED', 'PARTIALLY_REFUNDED')");
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Pitch", b =>
                {
                    b.Property<int>("PitchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PitchId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PitchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PitchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PitchId");

                    b.ToTable("Pitches", t =>
                        {
                            t.HasCheckConstraint("CK_Pitches_Status", "[Status] IN ('ACTIVE', 'MAINTENANCE', 'INACTIVE')");

                            t.HasCheckConstraint("CK_Pitches_Type", "[PitchType] IN ('5_PERSON', '7_PERSON', '11_PERSON')");
                        });

                    b.HasData(
                        new
                        {
                            PitchId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sân 5 người cỏ nhân tạo mới thay",
                            PitchName = "Sân 5A (Cỏ mới)",
                            PitchType = "5_PERSON",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            PitchId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sân 5 người, đá không sợ mưa",
                            PitchName = "Sân 5B (Có mái che)",
                            PitchType = "5_PERSON",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            PitchId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sân 7 người kích thước chuẩn",
                            PitchName = "Sân 7A (Tiêu chuẩn)",
                            PitchType = "7_PERSON",
                            Status = "ACTIVE"
                        },
                        new
                        {
                            PitchId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sân đang thay lưới và đèn",
                            PitchName = "Sân 7B (Bảo trì)",
                            PitchType = "7_PERSON",
                            Status = "MAINTENANCE"
                        },
                        new
                        {
                            PitchId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sân 11 người phục vụ giải đấu",
                            PitchName = "Sân 11 Lớn",
                            PitchType = "11_PERSON",
                            Status = "ACTIVE"
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.PriceSlot", b =>
                {
                    b.Property<int>("PriceSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriceSlotId"));

                    b.Property<string>("ApplyOn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsPeakHour")
                        .HasColumnType("bit");

                    b.Property<int>("PitchId")
                        .HasColumnType("int");

                    b.Property<string>("PitchType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PricePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("PriceSlotId");

                    b.HasIndex("PitchId");

                    b.ToTable("PriceSlots", t =>
                        {
                            t.HasCheckConstraint("CK_PriceSlot_ApplyOn", "[ApplyOn] IN ('WEEKDAY', 'WEEKEND', 'ALL')");

                            t.HasCheckConstraint("CK_PriceSlot_Time", "[StartTime] < [EndTime]");

                            t.HasCheckConstraint("CK_PriceSlot_Type", "[PitchType] IN ('5_PERSON', '7_PERSON', '11_PERSON')");
                        });

                    b.HasData(
                        new
                        {
                            PriceSlotId = 1,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 1,
                            PitchType = "5_PERSON",
                            PricePerHour = 200000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 2,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 1,
                            PitchType = "5_PERSON",
                            PricePerHour = 350000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 3,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 1,
                            PitchType = "5_PERSON",
                            PricePerHour = 250000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 4,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 1,
                            PitchType = "5_PERSON",
                            PricePerHour = 400000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 5,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 2,
                            PitchType = "5_PERSON",
                            PricePerHour = 220000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 6,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 2,
                            PitchType = "5_PERSON",
                            PricePerHour = 370000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 7,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 2,
                            PitchType = "5_PERSON",
                            PricePerHour = 270000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 8,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 2,
                            PitchType = "5_PERSON",
                            PricePerHour = 420000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 9,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 3,
                            PitchType = "7_PERSON",
                            PricePerHour = 400000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 10,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 3,
                            PitchType = "7_PERSON",
                            PricePerHour = 600000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 11,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 3,
                            PitchType = "7_PERSON",
                            PricePerHour = 450000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 12,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 3,
                            PitchType = "7_PERSON",
                            PricePerHour = 700000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 13,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 4,
                            PitchType = "7_PERSON",
                            PricePerHour = 380000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 14,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 4,
                            PitchType = "7_PERSON",
                            PricePerHour = 580000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 15,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 4,
                            PitchType = "7_PERSON",
                            PricePerHour = 430000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 16,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 4,
                            PitchType = "7_PERSON",
                            PricePerHour = 680000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 17,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 5,
                            PitchType = "11_PERSON",
                            PricePerHour = 800000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 18,
                            ApplyOn = "WEEKDAY",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 5,
                            PitchType = "11_PERSON",
                            PricePerHour = 1200000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 19,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsPeakHour = false,
                            PitchId = 5,
                            PitchType = "11_PERSON",
                            PricePerHour = 900000m,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            PriceSlotId = 20,
                            ApplyOn = "WEEKEND",
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsPeakHour = true,
                            PitchId = 5,
                            PitchType = "11_PERSON",
                            PricePerHour = 1400000m,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Refund", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BookingDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayRefundId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RefundAmount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("RefundMethod")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("RefundId");

                    b.HasIndex("BookingDetailId");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IDX_Refunds_Payment");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IDX_Refunds_Status");

                    b.ToTable("Refunds", t =>
                        {
                            t.HasCheckConstraint("CK_Refunds_Amount", "[RefundAmount] > 0");

                            t.HasCheckConstraint("CK_Refunds_Method", "[RefundMethod] IS NULL OR [RefundMethod] IN ('WALLET', 'BANK_TRANSFER', 'ORIGINAL_METHOD')");

                            t.HasCheckConstraint("CK_Refunds_Status", "[Status] IN ('PENDING', 'APPROVED', 'PROCESSING', 'COMPLETED', 'REJECTED')");
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.RefundPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolicyId"));

                    b.Property<int>("CancelBeforeHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("RefundPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("PolicyId");

                    b.ToTable("RefundPolicies", t =>
                        {
                            t.HasCheckConstraint("CK_RefundPolicy_Percentage", "[RefundPercentage] BETWEEN 0 AND 100");
                        });

                    b.HasData(
                        new
                        {
                            PolicyId = 1,
                            CancelBeforeHours = 72,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hủy trước 3 ngày (72h) - Hoàn 100%",
                            IsActive = true,
                            RefundPercentage = 100.00m
                        },
                        new
                        {
                            PolicyId = 2,
                            CancelBeforeHours = 48,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hủy trước 2 ngày (48h) - Hoàn 75%",
                            IsActive = true,
                            RefundPercentage = 75.00m
                        },
                        new
                        {
                            PolicyId = 3,
                            CancelBeforeHours = 24,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hủy trước 1 ngày (24h) - Hoàn 50%",
                            IsActive = true,
                            RefundPercentage = 50.00m
                        },
                        new
                        {
                            PolicyId = 4,
                            CancelBeforeHours = 12,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hủy trước 12 tiếng - Hoàn 20%",
                            IsActive = true,
                            RefundPercentage = 20.00m
                        },
                        new
                        {
                            PolicyId = 5,
                            CancelBeforeHours = 6,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hủy sát giờ (dưới 6 tiếng) - Không hoàn tiền",
                            IsActive = true,
                            RefundPercentage = 0.00m
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.StaffPitchAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PitchId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PitchId");

                    b.HasIndex("StaffId", "PitchId")
                        .IsUnique();

                    b.ToTable("StaffPitchAssignments");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.StaffShift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PitchId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftId");

                    b.HasIndex("PitchId");

                    b.HasIndex("StaffId", "PitchId", "DayOfWeek")
                        .HasDatabaseName("IDX_StaffShift_Lookup");

                    b.ToTable("StaffShifts", t =>
                        {
                            t.HasCheckConstraint("CK_StaffShift_DayOfWeek", "[DayOfWeek] BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CK_StaffShift_Time", "[StartTime] < [EndTime]");
                        });

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 2,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            IsActive = true,
                            PitchId = 1,
                            StaffId = 2,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            ShiftId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 3,
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsActive = true,
                            PitchId = 2,
                            StaffId = 2,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            ShiftId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 4,
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            IsActive = true,
                            PitchId = 3,
                            StaffId = 3,
                            StartTime = new TimeSpan(0, 6, 0, 0, 0)
                        },
                        new
                        {
                            ShiftId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 7,
                            EndTime = new TimeSpan(0, 22, 0, 0, 0),
                            IsActive = true,
                            PitchId = 5,
                            StaffId = 3,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            ShiftId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DayOfWeek = 1,
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            IsActive = true,
                            PitchId = 1,
                            StaffId = 2,
                            StartTime = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.TopUpRequest", b =>
                {
                    b.Property<int>("TopupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopupId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GatewayTransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProofImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TopupId");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasFilter("[TransactionId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("TopUpRequests", t =>
                        {
                            t.HasCheckConstraint("CK_TopUp_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_TopUp_Method", "[PaymentMethod] IN ('BANK_TRANSFER', 'VNPAY', 'MOMO', 'ZALOPAY')");

                            t.HasCheckConstraint("CK_TopUp_Status", "[Status] IN ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal>("BalanceBefore")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IDX_Transactions_Booking");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("IDX_Transactions_Ref");

                    b.HasIndex("WalletId", "CreatedAt")
                        .HasDatabaseName("IDX_Transactions_Wallet");

                    b.ToTable("Transactions", t =>
                        {
                            t.HasCheckConstraint("CK_Transactions_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Transactions_Direction", "[Direction] IN ('CREDIT', 'DEBIT')");

                            t.HasCheckConstraint("CK_Transactions_Status", "[Status] IN ('PENDING', 'SUCCESS', 'FAILED', 'REVERSED')");

                            t.HasCheckConstraint("CK_Transactions_Type", "[TransactionType] IN ('TOP_UP', 'BOOKING_PAYMENT', 'REFUND', 'WITHDRAWAL', 'ADJUSTMENT')");
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('ADMIN', 'STAFF', 'CUSTOMER')");
                        });

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@football.com",
                            FullName = "Admin Quản Trị",
                            IsActive = true,
                            Password = "$2a$11$IcrPPnD8wX2UaRxXKadYfOUAo7t7snZV914CKUKx40QdEgO30H68W",
                            Phone = "0901111111",
                            Role = "ADMIN"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff1@football.com",
                            FullName = "Nguyễn Văn A (Nhân viên 1)",
                            IsActive = true,
                            Password = "$2a$11$IcrPPnD8wX2UaRxXKadYfOUAo7t7snZV914CKUKx40QdEgO30H68W",
                            Phone = "0902222222",
                            Role = "STAFF"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "staff2@football.com",
                            FullName = "Trần Thị B (Nhân viên 2)",
                            IsActive = true,
                            Password = "$2a$11$IcrPPnD8wX2UaRxXKadYfOUAo7t7snZV914CKUKx40QdEgO30H68W",
                            Phone = "0903333333",
                            Role = "STAFF"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer1@gmail.com",
                            FullName = "Lê Khách C",
                            IsActive = true,
                            Password = "$2a$11$IcrPPnD8wX2UaRxXKadYfOUAo7t7snZV914CKUKx40QdEgO30H68W",
                            Phone = "0904444444",
                            Role = "CUSTOMER"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer2@gmail.com",
                            FullName = "Phạm Khách D",
                            IsActive = true,
                            Password = "$2a$11$IcrPPnD8wX2UaRxXKadYfOUAo7t7snZV914CKUKx40QdEgO30H68W",
                            Phone = "0905555555",
                            Role = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets", t =>
                        {
                            t.HasCheckConstraint("CK_Wallets_Balance", "[Balance] >= 0");
                        });
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Booking", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.BookingDetail", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.Pitch", "Pitch")
                        .WithMany("BookingDetails")
                        .HasForeignKey("PitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.User", "Staff")
                        .WithMany("AssignedBookingDetails")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("Pitch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.BookingStatusHistory", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.BookingDetail", "BookingDetail")
                        .WithMany("StatusHistories")
                        .HasForeignKey("BookingDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.User", "ChangedByUser")
                        .WithMany("BookingStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BookingDetail");

                    b.Navigation("ChangedByUser");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Payment", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.User", "ConfirmedByUser")
                        .WithMany("ConfirmedPayments")
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballBooking_BE.Data.Entities.Transaction", "Transaction")
                        .WithOne("Payment")
                        .HasForeignKey("FootballBooking_BE.Data.Entities.Payment", "TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.PriceSlot", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.Pitch", "Pitch")
                        .WithMany("PriceSlots")
                        .HasForeignKey("PitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pitch");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Refund", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.BookingDetail", "BookingDetail")
                        .WithMany("Refunds")
                        .HasForeignKey("BookingDetailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballBooking_BE.Data.Entities.Payment", "Payment")
                        .WithMany("Refunds")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.User", "RequestedByUser")
                        .WithMany("RequestedRefunds")
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.User", "ReviewedByUser")
                        .WithMany("ReviewedRefunds")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballBooking_BE.Data.Entities.Transaction", "Transaction")
                        .WithOne("Refund")
                        .HasForeignKey("FootballBooking_BE.Data.Entities.Refund", "TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BookingDetail");

                    b.Navigation("Payment");

                    b.Navigation("RequestedByUser");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.StaffPitchAssignment", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.Pitch", "Pitch")
                        .WithMany("StaffPitchAssignments")
                        .HasForeignKey("PitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.User", "Staff")
                        .WithMany("StaffPitchAssignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pitch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.StaffShift", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.Pitch", "Pitch")
                        .WithMany()
                        .HasForeignKey("PitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pitch");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.TopUpRequest", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.User", "ConfirmedByUser")
                        .WithMany("ConfirmedTopUps")
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballBooking_BE.Data.Entities.Transaction", "Transaction")
                        .WithOne("TopUpRequest")
                        .HasForeignKey("FootballBooking_BE.Data.Entities.TopUpRequest", "TransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballBooking_BE.Data.Entities.User", "User")
                        .WithMany("TopUpRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballBooking_BE.Data.Entities.Wallet", "Wallet")
                        .WithMany("TopUpRequests")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("Transaction");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Transaction", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.Booking", "Booking")
                        .WithMany("Transactions")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballBooking_BE.Data.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Wallet", b =>
                {
                    b.HasOne("FootballBooking_BE.Data.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("FootballBooking_BE.Data.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Payments");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.BookingDetail", b =>
                {
                    b.Navigation("Refunds");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Pitch", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("PriceSlots");

                    b.Navigation("StaffPitchAssignments");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Transaction", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Refund");

                    b.Navigation("TopUpRequest");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.User", b =>
                {
                    b.Navigation("AssignedBookingDetails");

                    b.Navigation("BookingStatusHistories");

                    b.Navigation("Bookings");

                    b.Navigation("ConfirmedPayments");

                    b.Navigation("ConfirmedTopUps");

                    b.Navigation("RequestedRefunds");

                    b.Navigation("ReviewedRefunds");

                    b.Navigation("StaffPitchAssignments");

                    b.Navigation("TopUpRequests");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("FootballBooking_BE.Data.Entities.Wallet", b =>
                {
                    b.Navigation("TopUpRequests");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
